spring:
  zipkin:
    base-url: ${ZIPKIN:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/slots}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Chemege1.}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  graphql:
    graphiql:
      enabled: true
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/slots}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Chemege1.}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true